### ISSUE TITLE
Use of Comments

### ISSUE THREAD

**Issue by mml1** [wbajem01/prj-rev-bwfs-dasmoto#1]
(Great!) Great use of comments in your HTML file!

https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/index.html#L23
https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/index.html#L17
https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/index.html#L11

**Comment by wbajem01** [comment]
I like to use comments but I don't always know what to say.
