### ISSUE TITLE
DRY Principle 

### ISSUE THREAD

**Issue by mml1** [wbajem01/prj-rev-bwfs-dasmoto#2]
(Simplify) I would like to introduce you to the DRY Principle, which is Do Not Repeat yourself. It is a commonly used best practice method. In your stylesheet, you repeat:

```
font-size: 32px;
font-weight: bold;
color: white;
```
Try wrapping your HTML elements for each section in a div and to apply these changes with a class. 

https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/resources/style.css#L17-L19
https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/resources/style.css#L24-L26
https://github.com/wbajem01/prj-rev-bwfs-dasmoto/blob/master/DesmotoArtsCraft/resources/style.css#L31-L33

**Comment by wbajem01** [comment]
Thanks and I will do that.
