### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by mml1** [wbajem01/prj-rev-bwfs-dasmoto#4]
[Meets Expectations] Excellent work! You're code is well formatted and easy to navigate. I liked how you even included the design spec in your comment. The only suggest I would have is to check where you are repeating code and see if you can simplify it. 

You are doing a fantastic job and writing professional looking code. As next steps, I would suggest you read about Semantic HTML tags. I think you would use them well.

**Comment by wbajem01** [comment]
Thank you very much. I will do that.
